import { useEffect, useState } from 'react';
import { CheckCircle2, LockKeyhole } from 'lucide-react';
import { API } from './api';
type Summary = { revenue: string; cash: string; pos: string; transfer: string; other: string; expenses: string; cogs: string; grossProfit: string; netProfit: string; transactions: number };
const money = (value: string | number) => `₦${Number(value).toLocaleString('en-NG', { maximumFractionDigits: 2 })}`;
const today = new Date().toISOString().slice(0, 10);
export function ClosingPage() { const [date, setDate] = useState(today); const [summary, setSummary] = useState<Summary | null>(null); const [closed, setClosed] = useState(false); const [closedBy, setClosedBy] = useState(''); const [message, setMessage] = useState(''); const load = () => fetch(`${API}/daily-closing?date=${date}`, { credentials: 'include' }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message); setSummary(data.summary); setClosed(Boolean(data.closing)); setClosedBy(data.closing?.closedBy?.name ?? ''); }).catch((error) => setMessage(error instanceof Error ? error.message : 'Unable to load closing summary.')); useEffect(() => { load(); }, [date]); const closeDay = async () => { const response = await fetch(`${API}/daily-closing`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ businessDate: date }) }); const data = await response.json(); setMessage(response.ok ? 'Business day closed successfully.' : data.message); if (response.ok) load(); }; return <section><div className="page-heading"><div><p className="eyebrow">CONTROL DESK</p><h1>Daily closing</h1><p className="muted">Review the day, then lock its financial records.</p></div><label className="date-picker">Business date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label></div>{message && <p className="success-message">{message}</p>}{summary && <><div className="summary-grid"><Metric label="Total sales" value={money(summary.revenue)} detail={`${summary.transactions} transactions`} accent="teal" /><Metric label="Cash sales" value={money(summary.cash)} detail="Recorded payments" /><Metric label="COGS" value={money(summary.cogs)} detail="Immutable cost snapshots" /><Metric label="Net profit" value={money(summary.netProfit)} detail={`After ${money(summary.expenses)} expenses`} accent="gold" /></div><div className="content-grid closing-grid"><section className="panel"><p className="eyebrow">PAYMENT RECONCILIATION</p><h2>Collected by method</h2><CloseRow label="Cash" value={summary.cash} /><CloseRow label="POS / Card" value={summary.pos} /><CloseRow label="Bank transfer" value={summary.transfer} /><CloseRow label="Other" value={summary.other} /></section><section className={`panel close-action ${closed ? 'is-closed' : ''}`}>{closed ? <><CheckCircle2 size={30} /><p className="eyebrow">DAY CLOSED</p><h2>Records are locked</h2><p className="muted">Closed by {closedBy || 'manager'}. Future corrections require a reversal or adjustment workflow.</p></> : <><LockKeyhole size={30} /><p className="eyebrow">READY TO CLOSE</p><h2>Lock {new Date(`${date}T00:00:00`).toLocaleDateString()}</h2><p className="muted">Normal financial edits will be prevented after closing.</p><button className="primary-button" onClick={closeDay}>Close day</button></>}</section></div></>}</section>; }
function Metric({ label, value, detail, accent = '' }: { label: string; value: string; detail: string; accent?: string }) { return <div className={`metric ${accent}`}><p>{label}</p><strong>{value}</strong><small>{detail}</small></div>; }
function CloseRow({ label, value }: { label: string; value: string }) { return <div className="close-row"><span>{label}</span><strong>{money(value)}</strong></div>; }
