import { useEffect, useState } from 'react';
import { Search, Plus, PackageOpen } from 'lucide-react';
import { API } from './api';

type Product = { id: string; name: string; sku: string; costPrice: string; sellingPrice: string; currentStock: number; minimumStock: number; unit: string; category?: { name: string } | null };
type InventoryItem = Product & { stockValue: string; status: 'IN_STOCK' | 'LOW_STOCK' | 'OUT_OF_STOCK' };
const money = (value: string | number) => `₦${Number(value).toLocaleString('en-NG', { maximumFractionDigits: 2 })}`;

export function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${API}/products?search=${encodeURIComponent(search)}`, { credentials: 'include' }).then((response) => response.json()).then((data) => setProducts(data.products ?? [])).finally(() => setLoading(false)); }, [search]);
  return <section><div className="page-heading"><div><p className="eyebrow">CATALOGUE</p><h1>Products</h1><p className="muted">Your active product catalogue and pricing.</p></div><button className="primary-button"><Plus size={16} /> Add product</button></div><div className="panel"><div className="table-toolbar"><div className="search-box"><Search size={16} /><input aria-label="Search products" placeholder="Search by product or SKU" value={search} onChange={(event) => setSearch(event.target.value)} /></div></div>{loading ? <p className="muted">Loading products...</p> : products.length === 0 ? <div className="empty-state"><PackageOpen size={28} /><strong>No products found</strong><span>Try a different search.</span></div> : <div className="data-table"><div className="table-head"><span>Product</span><span>SKU</span><span>Category</span><span>Cost price</span><span>Selling price</span><span>Status</span></div>{products.map((product) => <div className="table-row" key={product.id}><strong>{product.name}<small>{product.unit}</small></strong><span>{product.sku}</span><span>{product.category?.name ?? 'Uncategorised'}</span><span>{money(product.costPrice)}</span><span>{money(product.sellingPrice)}</span><span className="status healthy">Active</span></div>)}</div>}</div></section>;
}

export function InventoryPage() {
  const [inventory, setInventory] = useState<InventoryItem[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${API}/inventory`, { credentials: 'include' }).then((response) => response.json()).then((data) => setInventory(data.inventory ?? [])).finally(() => setLoading(false)); }, []);
  return <section><div className="page-heading"><div><p className="eyebrow">STOCK CONTROL</p><h1>Inventory</h1><p className="muted">Monitor quantity, value, and replenishment needs.</p></div></div><div className="summary-grid inventory-summary"><Metric label="Total SKUs" value={String(inventory.length)} detail="Active products" /><Metric label="Inventory value" value={money(inventory.reduce((total, item) => total + Number(item.stockValue), 0))} detail="At cost price" accent="teal" /><Metric label="Low stock" value={String(inventory.filter((item) => item.status === 'LOW_STOCK').length)} detail="Needs replenishment" accent="gold" /><Metric label="Out of stock" value={String(inventory.filter((item) => item.status === 'OUT_OF_STOCK').length)} detail="Immediate action" /></div><div className="panel inventory-panel"><div className="panel-heading"><div><p className="eyebrow">CURRENT LEVELS</p><h2>Stock ledger</h2></div></div>{loading ? <p className="muted">Loading inventory...</p> : <div className="data-table"><div className="table-head"><span>Product</span><span>SKU</span><span>Quantity</span><span>Min. stock</span><span>Stock value</span><span>Status</span></div>{inventory.map((item) => <div className="table-row" key={item.id}><strong>{item.name}<small>{item.unit}</small></strong><span>{item.sku}</span><span>{item.currentStock}</span><span>{item.minimumStock}</span><span>{money(item.stockValue)}</span><span className={`status ${item.status === 'IN_STOCK' ? 'healthy' : ''}`}>{item.status === 'IN_STOCK' ? 'In stock' : item.status === 'LOW_STOCK' ? 'Low stock' : 'Out of stock'}</span></div>)}</div>}</div></section>;
}
function Metric({ label, value, detail, accent = '' }: { label: string; value: string; detail: string; accent?: string }) { return <div className={`metric ${accent}`}><p>{label}</p><strong>{value}</strong><small>{detail}</small></div>; }
