import 'dotenv/config';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import express, { NextFunction, Request, Response } from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import { Prisma, PrismaClient, Role } from '@prisma/client';
import { z } from 'zod';

const prisma = new PrismaClient();
const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);
const loginSchema = { email: /^[^@\s]+@[^@\s]+\.[^@\s]+$/, password: /^.{8,}$/ };

declare global { namespace Express { interface Request { user?: { id: string; name: string; email: string; role: Role } } } }
app.use(cors({ origin: process.env.WEB_ORIGIN ?? 'http://localhost:5173', credentials: true }));
app.use(helmet());
app.use(express.json({ limit: '1mb' }));
app.use(cookieParser());

async function requireAuth(req: Request, res: Response, next: NextFunction) {
  const token = req.cookies.storeflow_session as string | undefined;
  const session = token ? await prisma.session.findUnique({ where: { id: token } }) : undefined;
  if (!session || session.expiresAt < new Date()) return res.status(401).json({ message: 'Authentication required' });
  const user = await prisma.user.findFirst({ where: { id: session.userId, isActive: true }, select: { id: true, name: true, email: true, role: true } });
  if (!user) return res.status(401).json({ message: 'Authentication required' });
  req.user = user;
  next();
}
function requireRole(...roles: Role[]) { return (req: Request, res: Response, next: NextFunction) => req.user && roles.includes(req.user.role) ? next() : res.status(403).json({ message: 'Insufficient permissions' }); }
const productInput = z.object({ name: z.string().trim().min(1).max(120), sku: z.string().trim().min(1).max(40), description: z.string().trim().max(500).optional(), costPrice: z.coerce.number().finite().nonnegative(), sellingPrice: z.coerce.number().finite().nonnegative(), currentStock: z.coerce.number().int().nonnegative().default(0), minimumStock: z.coerce.number().int().nonnegative().default(0), unit: z.string().trim().min(1).max(30).default('unit'), categoryId: z.string().cuid().nullable().optional() });
const stockAdjustmentInput = z.object({ quantity: z.coerce.number().int().refine((value) => value !== 0), type: z.enum(['STOCK_ADDED', 'STOCK_REMOVED', 'CORRECTION', 'DAMAGED', 'RETURNED', 'OTHER']), reason: z.string().trim().min(3).max(240) });
const itemInput = z.object({ productId: z.string().cuid(), quantity: z.coerce.number().int().positive().max(100000) });
const uniqueItems = (items: { productId: string }[]) => new Set(items.map((item) => item.productId)).size === items.length;
const saleInput = z.object({ businessDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), items: z.array(itemInput).min(1).refine(uniqueItems, 'Each product may appear only once per sale.'), discount: z.coerce.number().finite().nonnegative().default(0), paymentMethod: z.enum(['CASH', 'POS_CARD', 'BANK_TRANSFER', 'OTHER']), customerName: z.string().trim().max(120).optional(), customerPhone: z.string().trim().max(40).optional(), notes: z.string().trim().max(500).optional() });
const orderInput = z.object({ businessDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), items: z.array(itemInput).min(1).refine(uniqueItems, 'Each product may appear only once per order.'), discount: z.coerce.number().finite().nonnegative().default(0), customerName: z.string().trim().max(120).optional(), customerPhone: z.string().trim().max(40).optional(), notes: z.string().trim().max(500).optional() });
const orderStatusInput = z.object({ status: z.enum(['PENDING', 'CONFIRMED', 'PROCESSING', 'READY', 'COMPLETED', 'CANCELLED']) });
const orderPaymentInput = z.object({ amount: z.coerce.number().finite().positive(), method: z.enum(['CASH', 'POS_CARD', 'BANK_TRANSFER', 'OTHER']) });
const expenseInput = z.object({ businessDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), categoryId: z.string().cuid(), description: z.string().trim().min(3).max(240), amount: z.coerce.number().finite().positive(), paymentMethod: z.enum(['CASH', 'POS_CARD', 'BANK_TRANSFER', 'OTHER']), notes: z.string().trim().max(500).optional(), receiptUrl: z.string().url().max(500).optional() });
const expenseCategoryInput = z.object({ name: z.string().trim().min(2).max(80) });
const reportQuery = z.object({ startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/) });
const userInput = z.object({ name: z.string().trim().min(2).max(100), email: z.string().email().transform((value) => value.toLowerCase()), password: z.string().min(8).max(100), role: z.enum(['MANAGER', 'STAFF']) });
const dateValue = (value: string) => new Date(`${value}T00:00:00.000Z`);
async function assertBusinessDateOpen(client: Prisma.TransactionClient | PrismaClient, date: Date) { if (await client.dailyClosing.findUnique({ where: { businessDate: date }, select: { id: true } })) throw Object.assign(new Error('This business day is closed.'), { statusCode: 409 }); }

app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
app.get('/api/ready', async (_req, res) => { try { await prisma.$queryRaw`SELECT 1`; res.json({ status: 'ready' }); } catch { res.status(503).json({ status: 'unavailable' }); } });
app.post('/api/auth/login', rateLimit({ windowMs: 60_000, limit: 10 }), async (req, res, next) => {
  try {
    const email = String(req.body.email ?? '').toLowerCase().trim(); const password = String(req.body.password ?? '');
    if (!loginSchema.email.test(email) || !loginSchema.password.test(password)) return res.status(400).json({ message: 'Enter a valid email and password.' });
    const user = await prisma.user.findUnique({ where: { email } });
    if (!user || !user.isActive || !(await bcrypt.compare(password, user.passwordHash))) return res.status(401).json({ message: 'Invalid email or password.' });
    const token = crypto.randomBytes(32).toString('hex'); await prisma.session.create({ data: { id: token, userId: user.id, expiresAt: new Date(Date.now() + 8 * 60 * 60 * 1000) } });
    res.cookie('storeflow_session', token, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 8 * 60 * 60 * 1000 });
    await prisma.auditLog.create({ data: { action: 'LOGIN', entity: 'User', entityId: user.id, userId: user.id } });
    res.json({ user: { id: user.id, name: user.name, email: user.email, role: user.role } });
  } catch (error) { next(error); }
});
app.post('/api/auth/logout', requireAuth, async (req, res, next) => { try { const token = req.cookies.storeflow_session; if (token) await prisma.session.deleteMany({ where: { id: token } }); res.clearCookie('storeflow_session'); if (req.user) await prisma.auditLog.create({ data: { action: 'LOGOUT', entity: 'User', entityId: req.user.id, userId: req.user.id } }); res.status(204).end(); } catch (error) { next(error); } });
app.get('/api/auth/me', requireAuth, (req, res) => res.json({ user: req.user }));
app.get('/api/products', requireAuth, async (req, res, next) => { try { const search = String(req.query.search ?? '').trim(); const products = await prisma.product.findMany({ where: { isActive: true, ...(search ? { OR: [{ name: { contains: search, mode: 'insensitive' } }, { sku: { contains: search, mode: 'insensitive' } }] } : {}) }, include: { category: true }, orderBy: { name: 'asc' } }); res.json({ products }); } catch (error) { next(error); } });
app.post('/api/products', requireAuth, requireRole(Role.MANAGER), async (req, res, next) => { try { const parsed = productInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Check the product details and try again.' }); const product = await prisma.$transaction(async (tx) => { const created = await tx.product.create({ data: parsed.data }); await tx.auditLog.create({ data: { action: 'PRODUCT_CREATED', entity: 'Product', entityId: created.id, userId: req.user!.id, details: { sku: created.sku } } }); return created; }); res.status(201).json({ product }); } catch (error) { next(error); } });
app.patch('/api/products/:id', requireAuth, requireRole(Role.MANAGER), async (req, res, next) => { try { const parsed = productInput.partial().safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Check the product details and try again.' }); const product = await prisma.$transaction(async (tx) => { const updated = await tx.product.update({ where: { id: String(req.params.id) }, data: parsed.data }); await tx.auditLog.create({ data: { action: 'PRODUCT_UPDATED', entity: 'Product', entityId: updated.id, userId: req.user!.id } }); return updated; }); res.json({ product }); } catch (error) { next(error); } });
app.post('/api/products/:id/archive', requireAuth, requireRole(Role.MANAGER), async (req, res, next) => { try { const product = await prisma.$transaction(async (tx) => { const archived = await tx.product.update({ where: { id: String(req.params.id) }, data: { isActive: false } }); await tx.auditLog.create({ data: { action: 'PRODUCT_ARCHIVED', entity: 'Product', entityId: archived.id, userId: req.user!.id } }); return archived; }); res.json({ product }); } catch (error) { next(error); } });
app.get('/api/inventory', requireAuth, async (_req, res, next) => { try { const products = await prisma.product.findMany({ where: { isActive: true }, orderBy: { name: 'asc' } }); res.json({ inventory: products.map((product) => ({ ...product, stockValue: product.costPrice.mul(product.currentStock), status: product.currentStock === 0 ? 'OUT_OF_STOCK' : product.currentStock <= product.minimumStock ? 'LOW_STOCK' : 'IN_STOCK' })) }); } catch (error) { next(error); } });
app.get('/api/inventory/history', requireAuth, async (_req, res, next) => { try { const history = await prisma.inventoryTransaction.findMany({ include: { product: { select: { name: true, sku: true } }, user: { select: { name: true } } }, orderBy: { createdAt: 'desc' }, take: 100 }); res.json({ history }); } catch (error) { next(error); } });
app.post('/api/products/:id/stock-adjustment', requireAuth, requireRole(Role.MANAGER), async (req, res, next) => { try { const parsed = stockAdjustmentInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Enter a non-zero quantity and a reason.' }); const { quantity, type, reason } = parsed.data; const result = await prisma.$transaction(async (tx) => { await assertBusinessDateOpen(tx, dateValue(new Date().toISOString().slice(0, 10))); const product = await tx.product.findUnique({ where: { id: String(req.params.id) } }); if (!product || !product.isActive) throw Object.assign(new Error('Product not found.'), { statusCode: 404 }); const updated = await tx.product.updateMany({ where: { id: product.id, currentStock: { gte: quantity < 0 ? Math.abs(quantity) : 0 } }, data: { currentStock: { increment: quantity } } }); if (updated.count !== 1) throw Object.assign(new Error('Insufficient stock for this adjustment.'), { statusCode: 409 }); const nextQuantity = product.currentStock + quantity; const transaction = await tx.inventoryTransaction.create({ data: { productId: product.id, previousQuantity: product.currentStock, adjustmentQuantity: quantity, newQuantity: nextQuantity, type, reason, userId: req.user!.id } }); await tx.auditLog.create({ data: { action: 'INVENTORY_ADJUSTED', entity: 'Product', entityId: product.id, userId: req.user!.id, details: { quantity, type, reason } } }); return transaction; }); res.status(201).json({ transaction: result }); } catch (error) { next(error); } });
app.get('/api/sales', requireAuth, async (req, res, next) => { try { const sales = await prisma.sale.findMany({ where: { ...(req.query.date ? { businessDate: dateValue(String(req.query.date)) } : {}), ...(req.query.paymentMethod ? { payments: { some: { method: String(req.query.paymentMethod) as any } } } : {}) }, include: { recordedBy: { select: { name: true } }, items: { select: { quantity: true } }, payments: { select: { method: true } } }, orderBy: { createdAt: 'desc' }, take: 100 }); res.json({ sales }); } catch (error) { next(error); } });
app.get('/api/sales/daily-summary', requireAuth, async (req, res, next) => { try { const requestedDate = String(req.query.date ?? new Date().toISOString().slice(0, 10)); const businessDate = dateValue(requestedDate); const sales = await prisma.sale.findMany({ where: { businessDate, status: 'COMPLETED' }, include: { items: true, payments: true } }); const revenue = sales.reduce((total, sale) => total.add(sale.total), new Prisma.Decimal(0)); const discount = sales.reduce((total, sale) => total.add(sale.discount), new Prisma.Decimal(0)); const cogs = sales.reduce((total, sale) => total.add(sale.items.reduce((itemsTotal, item) => itemsTotal.add(item.unitCostPrice.mul(item.quantity)), new Prisma.Decimal(0))), new Prisma.Decimal(0)); const payments = ['CASH', 'POS_CARD', 'BANK_TRANSFER', 'OTHER'].map((method) => ({ method, amount: sales.flatMap((sale) => sale.payments).filter((payment) => payment.method === method).reduce((total, payment) => total.add(payment.amount), new Prisma.Decimal(0)) })); res.json({ date: requestedDate, summary: { revenue, discount, cogs, grossProfit: revenue.sub(cogs), transactions: sales.length, productsSold: sales.reduce((total, sale) => total + sale.items.reduce((itemsTotal, item) => itemsTotal + item.quantity, 0), 0) }, payments, sales }); } catch (error) { next(error); } });
app.get('/api/sales/:id', requireAuth, async (req, res, next) => { try { const sale = await prisma.sale.findUnique({ where: { id: String(req.params.id) }, include: { items: { include: { product: true } }, payments: true, recordedBy: { select: { name: true } } } }); if (!sale) return res.status(404).json({ message: 'Sale not found.' }); res.json({ sale }); } catch (error) { next(error); } });
app.post('/api/sales', requireAuth, async (req, res, next) => { try { const parsed = saleInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Check the sale items, payment, and date.' }); const input = parsed.data; const sale = await prisma.$transaction(async (tx) => { const businessDate = dateValue(input.businessDate); await assertBusinessDateOpen(tx, businessDate); const products = await Promise.all(input.items.map((item) => tx.product.findUnique({ where: { id: item.productId } }))); if (products.some((product) => !product || !product.isActive)) throw Object.assign(new Error('One or more products are unavailable.'), { statusCode: 400 }); const lines = input.items.map((item, index) => { const product = products[index]!; return { ...item, product, unitSellingPrice: new Prisma.Decimal(product.sellingPrice), unitCostPrice: new Prisma.Decimal(product.costPrice), subtotal: new Prisma.Decimal(product.sellingPrice).mul(item.quantity) }; }); const subtotal = lines.reduce((total, line) => total.add(line.subtotal), new Prisma.Decimal(0)); const discount = new Prisma.Decimal(input.discount); if (discount.gt(subtotal)) throw Object.assign(new Error('Discount cannot exceed the sale subtotal.'), { statusCode: 400 }); const total = subtotal.sub(discount); const created = await tx.sale.create({ data: { businessDate, customerName: input.customerName, customerPhone: input.customerPhone, notes: input.notes, discount, subtotal, total, recordedById: req.user!.id, items: { create: lines.map((line) => ({ productId: line.productId, quantity: line.quantity, unitSellingPrice: line.unitSellingPrice, unitCostPrice: line.unitCostPrice, subtotal: line.subtotal })) }, payments: { create: { amount: total, method: input.paymentMethod, recordedById: req.user!.id } } }, include: { items: true, payments: true } }); for (const line of lines) { const updated = await tx.product.updateMany({ where: { id: line.productId, isActive: true, currentStock: { gte: line.quantity } }, data: { currentStock: { decrement: line.quantity } } }); if (updated.count !== 1) throw Object.assign(new Error(`Insufficient stock for ${line.product.name}.`), { statusCode: 409 }); await tx.inventoryTransaction.create({ data: { productId: line.productId, previousQuantity: line.product.currentStock, adjustmentQuantity: -line.quantity, newQuantity: line.product.currentStock - line.quantity, type: 'SALE', reason: `Sale #${created.receiptNumber}`, saleId: created.id, userId: req.user!.id } }); } await tx.auditLog.create({ data: { action: 'SALE_CREATED', entity: 'Sale', entityId: created.id, userId: req.user!.id, details: { total: total.toString(), itemCount: lines.length } } }); return created; }); res.status(201).json({ sale }); } catch (error) { next(error); } });
app.post('/api/sales/:id/reverse', requireAuth, requireRole(Role.MANAGER), async (req, res, next) => { try { const sale = await prisma.$transaction(async (tx) => { const existing = await tx.sale.findUnique({ where: { id: String(req.params.id) }, include: { items: true, payments: true } }); if (!existing) throw Object.assign(new Error('Sale not found.'), { statusCode: 404 }); if (existing.status !== 'COMPLETED') throw Object.assign(new Error('Sale is already reversed.'), { statusCode: 409 }); await assertBusinessDateOpen(tx, existing.businessDate); for (const item of existing.items) { const product = await tx.product.findUniqueOrThrow({ where: { id: item.productId } }); await tx.product.update({ where: { id: product.id }, data: { currentStock: { increment: item.quantity } } }); await tx.inventoryTransaction.create({ data: { productId: product.id, previousQuantity: product.currentStock, adjustmentQuantity: item.quantity, newQuantity: product.currentStock + item.quantity, type: 'REVERSAL', reason: `Reversal of sale #${existing.receiptNumber}`, saleId: existing.id, userId: req.user!.id } }); } await tx.payment.updateMany({ where: { saleId: existing.id }, data: { status: 'REFUNDED' } }); const updated = await tx.sale.update({ where: { id: existing.id }, data: { status: 'REVERSED' }, include: { items: true, payments: true } }); await tx.auditLog.create({ data: { action: 'SALE_REVERSED', entity: 'Sale', entityId: existing.id, userId: req.user!.id } }); return updated; }); res.json({ sale }); } catch (error) { next(error); } });
app.get('/api/orders', requireAuth, async (_req, res, next) => { try { const orders = await prisma.order.findMany({ include: { createdBy: { select: { name: true } }, items: { select: { quantity: true } }, payments: { select: { amount: true, method: true } } }, orderBy: { createdAt: 'desc' }, take: 100 }); res.json({ orders }); } catch (error) { next(error); } });
app.get('/api/orders/:id', requireAuth, async (req, res, next) => { try { const order = await prisma.order.findUnique({ where: { id: String(req.params.id) }, include: { createdBy: { select: { name: true } }, items: { include: { product: true } }, payments: true } }); if (!order) return res.status(404).json({ message: 'Order not found.' }); res.json({ order }); } catch (error) { next(error); } });
app.post('/api/orders', requireAuth, async (req, res, next) => { try { const parsed = orderInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Check the order items, customer details, and date.' }); const input = parsed.data; const order = await prisma.$transaction(async (tx) => { const products = await Promise.all(input.items.map((item) => tx.product.findUnique({ where: { id: item.productId } }))); if (products.some((product) => !product || !product.isActive)) throw Object.assign(new Error('One or more products are unavailable.'), { statusCode: 400 }); const lines = input.items.map((item, index) => ({ ...item, unitPrice: products[index]!.sellingPrice, subtotal: new Prisma.Decimal(products[index]!.sellingPrice).mul(item.quantity) })); const subtotal = lines.reduce((total, line) => total.add(line.subtotal), new Prisma.Decimal(0)); const discount = new Prisma.Decimal(input.discount); if (discount.gt(subtotal)) throw Object.assign(new Error('Discount cannot exceed the order subtotal.'), { statusCode: 400 }); const created = await tx.order.create({ data: { businessDate: dateValue(input.businessDate), customerName: input.customerName, customerPhone: input.customerPhone, notes: input.notes, discount, subtotal, total: subtotal.sub(discount), createdById: req.user!.id, items: { create: lines.map((line) => ({ productId: line.productId, quantity: line.quantity, unitPrice: line.unitPrice, subtotal: line.subtotal })) } }, include: { items: true, payments: true } }); await tx.auditLog.create({ data: { action: 'ORDER_CREATED', entity: 'Order', entityId: created.id, userId: req.user!.id } }); return created; }); res.status(201).json({ order }); } catch (error) { next(error); } });
app.patch('/api/orders/:id/status', requireAuth, async (req, res, next) => { try { const parsed = orderStatusInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Invalid order status.' }); const order = await prisma.order.findUnique({ where: { id: String(req.params.id) } }); if (!order) return res.status(404).json({ message: 'Order not found.' }); const allowed: Record<string, string[]> = { PENDING: ['CONFIRMED', 'CANCELLED'], CONFIRMED: ['PROCESSING', 'CANCELLED'], PROCESSING: ['READY', 'CANCELLED'], READY: ['COMPLETED', 'CANCELLED'], COMPLETED: [], CANCELLED: [] }; if (!allowed[order.status]?.includes(parsed.data.status)) return res.status(409).json({ message: 'That order status change is not permitted.' }); const updated = await prisma.$transaction(async (tx) => { const result = await tx.order.update({ where: { id: order.id }, data: { status: parsed.data.status } }); await tx.auditLog.create({ data: { action: 'ORDER_STATUS_CHANGED', entity: 'Order', entityId: order.id, userId: req.user!.id, details: { from: order.status, to: parsed.data.status } } }); return result; }); res.json({ order: updated }); } catch (error) { next(error); } });
app.post('/api/orders/:id/payments', requireAuth, async (req, res, next) => { try { const parsed = orderPaymentInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Enter a valid payment amount and method.' }); const payment = await prisma.$transaction(async (tx) => { const order = await tx.order.findUnique({ where: { id: String(req.params.id) }, include: { payments: true } }); if (!order) throw Object.assign(new Error('Order not found.'), { statusCode: 404 }); await assertBusinessDateOpen(tx, order.businessDate); const paid = order.payments.reduce((total, item) => total.add(item.amount), new Prisma.Decimal(0)); const amount = new Prisma.Decimal(parsed.data.amount); if (paid.add(amount).gt(order.total)) throw Object.assign(new Error('Payment cannot exceed the order balance.'), { statusCode: 400 }); const result = await tx.payment.create({ data: { orderId: order.id, amount, method: parsed.data.method, recordedById: req.user!.id } }); const nextPaid = paid.add(amount); await tx.order.update({ where: { id: order.id }, data: { paymentStatus: nextPaid.eq(0) ? 'UNPAID' : nextPaid.gte(order.total) ? 'PAID' : 'PARTIALLY_PAID' } }); return result; }); res.status(201).json({ payment }); } catch (error) { next(error); } });
app.get('/api/expense-categories', requireAuth, async (_req, res, next) => { try { const categories = await prisma.expenseCategory.findMany({ where: { isActive: true }, orderBy: { name: 'asc' } }); res.json({ categories }); } catch (error) { next(error); } });
app.post('/api/expense-categories', requireAuth, requireRole(Role.MANAGER), async (req, res, next) => { try { const parsed = expenseCategoryInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Enter a valid category name.' }); const category = await prisma.expenseCategory.create({ data: parsed.data }); res.status(201).json({ category }); } catch (error) { next(error); } });
app.get('/api/expenses', requireAuth, async (req, res, next) => { try { const expenses = await prisma.expense.findMany({ where: { ...(req.query.date ? { businessDate: dateValue(String(req.query.date)) } : {}), ...(req.query.categoryId ? { categoryId: String(req.query.categoryId) } : {}) }, include: { category: true, recordedBy: { select: { name: true } } }, orderBy: { businessDate: 'desc' }, take: 100 }); res.json({ expenses }); } catch (error) { next(error); } });
app.post('/api/expenses', requireAuth, async (req, res, next) => { try { const parsed = expenseInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Check the expense date, category, description, and amount.' }); const input = parsed.data; const expense = await prisma.$transaction(async (tx) => { const businessDate = dateValue(input.businessDate); await assertBusinessDateOpen(tx, businessDate); const category = await tx.expenseCategory.findFirst({ where: { id: input.categoryId, isActive: true } }); if (!category) throw Object.assign(new Error('Expense category not found.'), { statusCode: 400 }); const created = await tx.expense.create({ data: { ...input, businessDate, amount: new Prisma.Decimal(input.amount), recordedById: req.user!.id } }); await tx.auditLog.create({ data: { action: 'EXPENSE_CREATED', entity: 'Expense', entityId: created.id, userId: req.user!.id } }); return created; }); res.status(201).json({ expense }); } catch (error) { next(error); } });
app.get('/api/reports/custom', requireAuth, async (req, res, next) => { try { const parsed = reportQuery.safeParse({ startDate: req.query.startDate, endDate: req.query.endDate }); if (!parsed.success) return res.status(400).json({ message: 'Choose a valid start and end date.' }); const startDate = dateValue(parsed.data.startDate); const endDate = dateValue(parsed.data.endDate); endDate.setUTCDate(endDate.getUTCDate() + 1); if (endDate <= startDate) return res.status(400).json({ message: 'End date must be on or after start date.' }); const [sales, expenses, paymentGroups, expenseGroups, bestSellers] = await Promise.all([prisma.sale.findMany({ where: { businessDate: { gte: startDate, lt: endDate }, status: 'COMPLETED' }, include: { items: { include: { product: { select: { name: true } } } }, payments: true } }), prisma.expense.findMany({ where: { businessDate: { gte: startDate, lt: endDate } }, include: { category: { select: { name: true } } } }), prisma.payment.groupBy({ by: ['method'], where: { sale: { businessDate: { gte: startDate, lt: endDate }, status: 'COMPLETED' } }, _sum: { amount: true } }), prisma.expense.groupBy({ by: ['categoryId'], where: { businessDate: { gte: startDate, lt: endDate } }, _sum: { amount: true } }), prisma.saleItem.groupBy({ by: ['productId'], where: { sale: { businessDate: { gte: startDate, lt: endDate }, status: 'COMPLETED' } }, _sum: { quantity: true }, orderBy: { _sum: { quantity: 'desc' } }, take: 5 })]); const revenue = sales.reduce((total, sale) => total.add(sale.total), new Prisma.Decimal(0)); const cogs = sales.reduce((total, sale) => total.add(sale.items.reduce((itemsTotal, item) => itemsTotal.add(item.unitCostPrice.mul(item.quantity)), new Prisma.Decimal(0))), new Prisma.Decimal(0)); const operatingExpenses = expenses.reduce((total, expense) => total.add(expense.amount), new Prisma.Decimal(0)); res.json({ summary: { revenue, cogs, grossProfit: revenue.sub(cogs), expenses: operatingExpenses, netProfit: revenue.sub(cogs).sub(operatingExpenses), salesCount: sales.length, productsSold: sales.reduce((total, sale) => total + sale.items.reduce((itemsTotal, item) => itemsTotal + item.quantity, 0), 0) }, paymentMethods: paymentGroups, expensesByCategory: expenseGroups, bestSellers }); } catch (error) { next(error); } });
app.get('/api/daily-closing', requireAuth, async (req, res, next) => { try { const requestedDate = String(req.query.date ?? new Date().toISOString().slice(0, 10)); const businessDate = dateValue(requestedDate); const nextDate = new Date(businessDate); nextDate.setUTCDate(nextDate.getUTCDate() + 1); const [sales, expenses, closing] = await Promise.all([prisma.sale.findMany({ where: { businessDate, status: 'COMPLETED' }, include: { items: true, payments: true } }), prisma.expense.findMany({ where: { businessDate } }), prisma.dailyClosing.findUnique({ where: { businessDate }, include: { closedBy: { select: { name: true } } } })]); const revenue = sales.reduce((total, sale) => total.add(sale.total), new Prisma.Decimal(0)); const cogs = sales.reduce((total, sale) => total.add(sale.items.reduce((itemsTotal, item) => itemsTotal.add(item.unitCostPrice.mul(item.quantity)), new Prisma.Decimal(0))), new Prisma.Decimal(0)); const operatingExpenses = expenses.reduce((total, expense) => total.add(expense.amount), new Prisma.Decimal(0)); const payments = ['CASH', 'POS_CARD', 'BANK_TRANSFER', 'OTHER'].map((method) => ({ method, amount: sales.flatMap((sale) => sale.payments).filter((payment) => payment.method === method).reduce((total, payment) => total.add(payment.amount), new Prisma.Decimal(0)) })); res.json({ businessDate, closing, summary: { revenue, cash: payments[0].amount, pos: payments[1].amount, transfer: payments[2].amount, other: payments[3].amount, expenses: operatingExpenses, cogs, grossProfit: revenue.sub(cogs), netProfit: revenue.sub(cogs).sub(operatingExpenses), transactions: sales.length }, payments }); } catch (error) { next(error); } });
app.post('/api/daily-closing', requireAuth, requireRole(Role.MANAGER), async (req, res, next) => { try { const parsed = z.object({ businessDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/) }).safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Choose a valid business date.' }); const businessDate = dateValue(parsed.data.businessDate); const closing = await prisma.$transaction(async (tx) => { const existing = await tx.dailyClosing.findUnique({ where: { businessDate } }); if (existing) throw Object.assign(new Error('This day is already closed.'), { statusCode: 409 }); const created = await tx.dailyClosing.create({ data: { businessDate, closedById: req.user!.id } }); await tx.auditLog.create({ data: { action: 'DAILY_CLOSING', entity: 'DailyClosing', entityId: created.id, userId: req.user!.id, details: { businessDate: parsed.data.businessDate } } }); return created; }); res.status(201).json({ closing }); } catch (error) { next(error); } });
app.get('/api/users', requireAuth, requireRole(Role.MANAGER), async (_req, res, next) => { try { const users = await prisma.user.findMany({ select: { id: true, name: true, email: true, role: true, isActive: true, createdAt: true }, orderBy: { name: 'asc' } }); res.json({ users }); } catch (error) { next(error); } });
app.post('/api/users', requireAuth, requireRole(Role.MANAGER), async (req, res, next) => { try { const parsed = userInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: 'Enter a valid name, email, role, and password.' }); const user = await prisma.$transaction(async (tx) => { const created = await tx.user.create({ data: { name: parsed.data.name, email: parsed.data.email, passwordHash: await bcrypt.hash(parsed.data.password, 12), role: parsed.data.role } }); await tx.auditLog.create({ data: { action: 'USER_CREATED', entity: 'User', entityId: created.id, userId: req.user!.id, details: { role: created.role } } }); return created; }); res.status(201).json({ user: { id: user.id, name: user.name, email: user.email, role: user.role, isActive: user.isActive } }); } catch (error) { next(error); } });
app.post('/api/users/:id/disable', requireAuth, requireRole(Role.MANAGER), async (req, res, next) => { try { if (String(req.params.id) === req.user!.id) return res.status(400).json({ message: 'You cannot disable your own account.' }); const user = await prisma.$transaction(async (tx) => { const updated = await tx.user.update({ where: { id: String(req.params.id) }, data: { isActive: false } }); await tx.session.deleteMany({ where: { userId: updated.id } }); await tx.auditLog.create({ data: { action: 'USER_DISABLED', entity: 'User', entityId: updated.id, userId: req.user!.id } }); return updated; }); res.json({ user: { id: user.id, name: user.name, email: user.email, role: user.role, isActive: user.isActive } }); } catch (error) { next(error); } });
app.get('/api/audit-logs', requireAuth, requireRole(Role.MANAGER), async (_req, res, next) => { try { const logs = await prisma.auditLog.findMany({ include: { user: { select: { name: true, email: true } } }, orderBy: { createdAt: 'desc' }, take: 200 }); res.json({ logs }); } catch (error) { next(error); } });
app.get('/api/dashboard', requireAuth, async (_req, res, next) => { try { const start = new Date(); start.setHours(0, 0, 0, 0); const [sales, expenses, products, orders] = await Promise.all([prisma.sale.aggregate({ where: { businessDate: start, status: 'COMPLETED' }, _sum: { total: true }, _count: true }), prisma.expense.aggregate({ where: { businessDate: start }, _sum: { amount: true } }), prisma.product.count({ where: { isActive: true } }), prisma.order.count({ where: { businessDate: start } })]); res.json({ sales: sales._sum.total ?? 0, expenses: expenses._sum.amount ?? 0, salesCount: sales._count, products, orders }); } catch (error) { next(error); } });
app.get('/api/manager-check', requireAuth, requireRole(Role.MANAGER), (_req, res) => res.json({ ok: true }));
app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { console.error(error); const statusCode = typeof error === 'object' && error !== null && 'statusCode' in error && typeof error.statusCode === 'number' ? error.statusCode : 500; res.status(statusCode).json({ message: statusCode === 500 ? 'Something went wrong.' : (error as Error).message }); });

if (require.main === module) { const server = app.listen(Number(process.env.PORT ?? process.env.API_PORT ?? 4000), () => console.log('StoreFlow API listening')); const shutdown = async () => { server.close(); await prisma.$disconnect(); }; process.once('SIGTERM', shutdown); process.once('SIGINT', shutdown); }
export { app };
